variables:
  URL_REGISTRE_IMAGE: "registre.priv.iutdelens.ovh"
  URL_DOCKERHUB: "dockerhub.priv.iutdelens.ovh"
  IMAGE : "${USER_LOGIN}/${CI_PROJECT_NAME}/client:${CI_COMMIT_SHORT_SHA}"
  URL_WEBSITE : "groupe1.priv.iutdelens.ovh"

image: dockerhub.priv.iutdelens.ovh/node:latest
# This folder is cached between builds
cache:
  paths:
    - node_modules/

stages:
  - config
  - test
  - analyse
  - build

config:
  stage: config
  tags:
    - "sae-s4a01"
  script:
    - npm install

test:
  stage: test
  tags:
    - "sae-s4a01"
  script:
    - node_modules/qunit/bin/qunit.js

eslint:
  stage: analyse
  tags:
    - "sae-s4a01"
  script:
    - npm run lint
  allow_failure: true


build-image:
  stage: build
  tags:
    - "sae-s4a01"
  image:
      name: gcr.io/kaniko-project/executor:v1.9.2-debug
      entrypoint: [""]
  script:
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"${URL_REGISTRE_IMAGE}\":{\"auth\":\"$(printf "%s:%s" "${USER_LOGIN}" "${PASSWORD_IUT}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        - >-
          /kaniko/executor
          --context "${CI_PROJECT_DIR}"
          --dockerfile "${CI_PROJECT_DIR}/Dockerfile-prod"
          --destination "${URL_REGISTRE_IMAGE}/${IMAGE}"
  when: manual
